### ISSUE TITLE
安装PIP库有报错

### ISSUE THREAD

**Issue by JanyXian** [lijiaxing1997/Gr33k#11]
bjoern==3.1.0安装失败

**Comment by JanyXian** [comment]
error: command 'i686-linux-gnu-gcc' failed with exit status 1

**Comment by lijiaxing1997** [comment]
直接运行，看看报什么错，缺什么装什么把。

**Comment by JanyXian** [comment]
RROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fczor94j/bjoern_20034c7ec0ff4c76bd3a20493a226884/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fczor94j/bjoern_20034c7ec0ff4c76bd3a20493a226884/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6z7x50hs                                                                 
       cwd: /tmp/pip-install-fczor94j/bjoern_20034c7ec0ff4c76bd3a20493a226884/                                                      
  Complete output (19 lines):                                                                                                       
  running bdist_wheel                                                                                                               
  running build                                                                                                                     
  running build_py                                                                                                                  
  creating build                                                                                                                    
  creating build/lib.linux-x86_64-3.9                                                                                               
  copying bjoern.py -> build/lib.linux-x86_64-3.9                                                                                   
  running build_ext                                                                                                                 
  building '_bjoern' extension                                                                                                      
  creating build/temp.linux-x86_64-3.9                                                                                              
  creating build/temp.linux-x86_64-3.9/bjoern                                                                                       
  creating build/temp.linux-x86_64-3.9/http-parser                                                                                  
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DSIGNAL_CHECK_INTERVAL=0.1 -DWANT_SIGNAL_HANDLING=yes -DWANT_SIGINT_HANDLING=yes -Ihttp-parser -Istatsd-c-client -I/usr/include/libev -I/opt/local/include -I/usr/include/python3.9 -c bjoern/_bjoernmodule.c -o build/temp.linux-x86_64-3.9/bjoern/_bjoernmodule.o -std=c99 -fno-strict-aliasing -fcommon -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -g                         
  In file included from bjoern/wsgi.h:2,                                                                                            
                   from bjoern/_bjoernmodule.c:3:                                                                                   
  bjoern/request.h:4:10: fatal error: ev.h: No such file or directory                                                               
      4 | #include <ev.h>                                                                                                           
        |          ^~~~~~                                                                                                           
  compilation terminated.                                                                                                           
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1                                                            
  ----------------------------------------                                                                                          
  ERROR: Failed building wheel for bjoern

**Comment by JanyXian** [comment]
一直报这个错误

**Comment by JanyXian** [comment]
安装您的安装方式进行部署在kali

**Comment by lijiaxing1997** [comment]
邮件发微信号给我吧，我加你看一下

**Comment by JanyXian** [comment]
已发

**Comment by lijiaxing1997** [comment]
没收到呢

**Comment by lijiaxing1997** [comment]
jiaxingl@126.com

**Comment by JanyXian** [comment]
已重新发

**Comment by JanyXian** [comment]
重发微信二维码过去
