### ISSUE TITLE
mac下报错，求解决

### ISSUE THREAD

**Issue by lyx52888** [lijiaxing1997/Gr33k#12]
![image](https://user-images.githubusercontent.com/76137672/125434392-7fa5bcaf-db0a-4d8f-a202-de50378d13ed.png)
ERROR:root:current PATH: /Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/homebrew/Homebrew/bin:/usr/local/homebrew/Homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public

**Comment by lijiaxing1997** [comment]
这个错误可以忽略，能正常启动就可以
