### ISSUE TITLE
依赖报错

### ISSUE THREAD

**Issue by littlebin404** [lijiaxing1997/Gr33k#8]
ERROR: Could not find a version that satisfies the requirement BeautifulSoup==3.2.2 (from versions: 3.2.0, 3.2.1, 3.2.2)
ERROR: No matching distribution found for BeautifulSoup==3.2.2

**Comment by endual** [comment]
同上，依赖报错。
mac os系统

**Comment by lijiaxing1997** [comment]
BeautifulSoup 尝试用pip3装一下

**Comment by lijiaxing1997** [comment]
我更新了新的requirements.txt

**Comment by littlebin404** [comment]
更新requirements.txt之后，报错变成这样了：
ERROR: Could not find a version that satisfies the requirement bjoern==3.1.0 (from versions: 1.0, 1.1, 1.1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 3.0.0, 3.0.1, 3.1.0)
ERROR: No matching distribution found for bjoern==3.1.0

**Comment by lijiaxing1997** [comment]
直接跳过，可能不需要这个

**Comment by NextAbyss** [comment]
> 直接跳过，可能不需要这个

我手动把pymssql版本改成仓库里最高版本2.2.1  然后依赖没报错   报了其他红字 我看了下还是pymssql的问题   我想问问你的pymssql 2.1.4版本哪来的啊。。。。

**Comment by lijiaxing1997** [comment]
您可以邮件我一下，我帮您解决一下

**Comment by NextAbyss** [comment]
> 您可以邮件我一下，我帮您解决一下

手动更改requirements版本号 解决了  非常谢谢
