### ISSUE TITLE
mac安装报错

### ISSUE THREAD

**Issue by Cu0rly** [lijiaxing1997/Gr33k#9]
进行到这一步：    Running setup.py install for gevent ... /
然后后面就开始报错，加权限也不行：
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/8d39b3qd4cxgphmrx1tt_gb40000gn/T/pip-install-lawo_uz8/gevent/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/8d39b3qd4cxgphmrx1tt_gb40000gn/T/pip-install-lawo_uz8/gevent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b7/8d39b3qd4cxgphmrx1tt_gb40000gn/T/pip-record-_v5mlgze/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/gevent Check the logs for full command output.

**Comment by lijiaxing1997** [comment]
这个模块跳过看一下

**Comment by Cu0rly** [comment]
帅
